name: Backend CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  backend-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Validate FastAPI Import
        run: |
          cd backend
          python -c "from app.main import app; print('Application Loaded Successfully')"